//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDzienny_.MCDzienny.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Command {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Command() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDzienny_.MCDzienny.Lang.Command", typeof(Command).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time modified:&amp;2 {0}.
        /// </summary>
        internal static string AboutDateOfModification {
            get {
                return ResourceManager.GetString("AboutDateOfModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutName {
            get {
                return ResourceManager.GetString("AboutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This block has not been modified since the map was cleared..
        /// </summary>
        internal static string AboutNoModification {
            get {
                return ResourceManager.GetString("AboutNoModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /afk &lt;reason&gt; - mark yourself as AFK. Use again to mark yourself as back.
        /// </summary>
        internal static string AfkHelp {
            get {
                return ResourceManager.GetString("AfkHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0}- is AFK {1}.
        /// </summary>
        internal static string AfkMessage {
            get {
                return ResourceManager.GetString("AfkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is AFK {1}.
        /// </summary>
        internal static string AfkMessage1 {
            get {
                return ResourceManager.GetString("AfkMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0}- is no longer AFK.
        /// </summary>
        internal static string AfkMessage2 {
            get {
                return ResourceManager.GetString("AfkMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no longer AFK.
        /// </summary>
        internal static string AfkMessage3 {
            get {
                return ResourceManager.GetString("AfkMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AfkName {
            get {
                return ResourceManager.GetString("AfkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /alive - Displays list of players that are still alive..
        /// </summary>
        internal static string AliveHelp {
            get {
                return ResourceManager.GetString("AliveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following players are still alive:.
        /// </summary>
        internal static string AliveMessage {
            get {
                return ResourceManager.GetString("AliveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AliveName {
            get {
                return ResourceManager.GetString("AliveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /award &lt;give/take&gt; [player] [award] - Gives [player] the [award].
        /// </summary>
        internal static string AwardHelp {
            get {
                return ResourceManager.GetString("AwardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no Give or Take is given, Give is used.
        /// </summary>
        internal static string AwardHelp1 {
            get {
                return ResourceManager.GetString("AwardHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [award] needs to be the full award&apos;s name. Not partial.
        /// </summary>
        internal static string AwardHelp2 {
            get {
                return ResourceManager.GetString("AwardHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The award you entered doesn&apos;t exist.
        /// </summary>
        internal static string AwardMessage {
            get {
                return ResourceManager.GetString("AwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use /awards for a list of awards.
        /// </summary>
        internal static string AwardMessage1 {
            get {
                return ResourceManager.GetString("AwardMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was awarded:%b {1}.
        /// </summary>
        internal static string AwardMessage2 {
            get {
                return ResourceManager.GetString("AwardMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player already has that award!.
        /// </summary>
        internal static string AwardMessage3 {
            get {
                return ResourceManager.GetString("AwardMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had their%b {1} award removed..
        /// </summary>
        internal static string AwardMessage4 {
            get {
                return ResourceManager.GetString("AwardMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player didn&apos;t have the award you tried to take.
        /// </summary>
        internal static string AwardMessage5 {
            get {
                return ResourceManager.GetString("AwardMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /awardmod &lt;add/del&gt; [award name] : [description].
        /// </summary>
        internal static string AwardModHelp {
            get {
                return ResourceManager.GetString("AwardModHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or deletes a reward with the name [award name].
        /// </summary>
        internal static string AwardModHelp1 {
            get {
                return ResourceManager.GetString("AwardModHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;b/awardmod add Bomb joy : Bomb lots of people {0} is an example.
        /// </summary>
        internal static string AwardModHelp2 {
            get {
                return ResourceManager.GetString("AwardModHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;cMissing a colon!.
        /// </summary>
        internal static string AwardModMessage {
            get {
                return ResourceManager.GetString("AwardModMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This award already exists!.
        /// </summary>
        internal static string AwardModMessage1 {
            get {
                return ResourceManager.GetString("AwardModMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award added:&amp;6 {0} : {1}.
        /// </summary>
        internal static string AwardModMessage2 {
            get {
                return ResourceManager.GetString("AwardModMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This award doesn&apos;t exists!.
        /// </summary>
        internal static string AwardModMessage3 {
            get {
                return ResourceManager.GetString("AwardModMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award removed:&amp;6 {0}.
        /// </summary>
        internal static string AwardModMessage4 {
            get {
                return ResourceManager.GetString("AwardModMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AwardModName {
            get {
                return ResourceManager.GetString("AwardModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string AwardModParameter {
            get {
                return ResourceManager.GetString("AwardModParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to del.
        /// </summary>
        internal static string AwardModParameter1 {
            get {
                return ResourceManager.GetString("AwardModParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AwardName {
            get {
                return ResourceManager.GetString("AwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give.
        /// </summary>
        internal static string AwardParameter {
            get {
                return ResourceManager.GetString("AwardParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take.
        /// </summary>
        internal static string AwardParameter1 {
            get {
                return ResourceManager.GetString("AwardParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ban &lt;player&gt; - Bans a player without kicking him..
        /// </summary>
        internal static string BanHelp {
            get {
                return ResourceManager.GetString("BanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add # before name to stealth ban..
        /// </summary>
        internal static string BanHelp1 {
            get {
                return ResourceManager.GetString("BanHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add @ before name to total ban..
        /// </summary>
        internal static string BanHelp2 {
            get {
                return ResourceManager.GetString("BanHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /banip &lt;ip/name&gt; - Bans an ip. Also accepts a player name when you use @ before the name..
        /// </summary>
        internal static string BanIPHelp {
            get {
                return ResourceManager.GetString("BanIPHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an IP address for that user..
        /// </summary>
        internal static string BanIPMessage {
            get {
                return ResourceManager.GetString("BanIPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t ip-ban the server!.
        /// </summary>
        internal static string BanIPMessage1 {
            get {
                return ResourceManager.GetString("BanIPMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP!.
        /// </summary>
        internal static string BanIPMessage2 {
            get {
                return ResourceManager.GetString("BanIPMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t ip-ban yourself.!.
        /// </summary>
        internal static string BanIPMessage3 {
            get {
                return ResourceManager.GetString("BanIPMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already ip-banned..
        /// </summary>
        internal static string BanIPMessage4 {
            get {
                return ResourceManager.GetString("BanIPMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} got &amp;8ip-banned!.
        /// </summary>
        internal static string BanIPMessage5 {
            get {
                return ResourceManager.GetString("BanIPMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-BANNED: {0} by {1}.
        /// </summary>
        internal static string BanIPMessage6 {
            get {
                return ResourceManager.GetString("BanIPMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-BANNED: {0} by console.
        /// </summary>
        internal static string BanIPMessage7 {
            get {
                return ResourceManager.GetString("BanIPMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BanIPName {
            get {
                return ResourceManager.GetString("BanIPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\&quot;.&quot;, &quot;Invalid name \.
        /// </summary>
        internal static string BanMessage {
            get {
                return ResourceManager.GetString("BanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t ban a {0}!.
        /// </summary>
        internal static string BanMessage1 {
            get {
                return ResourceManager.GetString("BanMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already banned..
        /// </summary>
        internal static string BanMessage2 {
            get {
                return ResourceManager.GetString("BanMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &amp;f(offline){1} is now &amp;8banned{1}!.
        /// </summary>
        internal static string BanMessage3 {
            get {
                return ResourceManager.GetString("BanMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now STEALTH &amp;8banned{1}!.
        /// </summary>
        internal static string BanMessage4 {
            get {
                return ResourceManager.GetString("BanMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now &amp;8banned{1}!.
        /// </summary>
        internal static string BanMessage5 {
            get {
                return ResourceManager.GetString("BanMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was banned..
        /// </summary>
        internal static string BanMessage6 {
            get {
                return ResourceManager.GetString("BanMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BanName {
            get {
                return ResourceManager.GetString("BanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /topten - Displays names of ten best players..
        /// </summary>
        internal static string BestScoresHelp {
            get {
                return ResourceManager.GetString("BestScoresHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top ten round scores:.
        /// </summary>
        internal static string BestScoresMessage {
            get {
                return ResourceManager.GetString("BestScoresMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %c{0}. {1} - best score: {2}.
        /// </summary>
        internal static string BestScoresMessage1 {
            get {
                return ResourceManager.GetString("BestScoresMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BestScoresName {
            get {
                return ResourceManager.GetString("BestScoresName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /bind &lt;block&gt; [type] - Replaces block with type..
        /// </summary>
        internal static string BindHelp {
            get {
                return ResourceManager.GetString("BindHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /bind clear - Clears all binds..
        /// </summary>
        internal static string BindHelp1 {
            get {
                return ResourceManager.GetString("BindHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All bindings were unbound..
        /// </summary>
        internal static string BindMessage {
            get {
                return ResourceManager.GetString("BindMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no block \&quot;{0}\&quot;..
        /// </summary>
        internal static string BindMessage1 {
            get {
                return ResourceManager.GetString("BindMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound {0}..
        /// </summary>
        internal static string BindMessage10 {
            get {
                return ResourceManager.GetString("BindMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.Command.BindMessage1.
        /// </summary>
        internal static string BindMessage2 {
            get {
                return ResourceManager.GetString("BindMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t a special block..
        /// </summary>
        internal static string BindMessage3 {
            get {
                return ResourceManager.GetString("BindMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t bind {0}..
        /// </summary>
        internal static string BindMessage4 {
            get {
                return ResourceManager.GetString("BindMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind anything to this block..
        /// </summary>
        internal static string BindMessage5 {
            get {
                return ResourceManager.GetString("BindMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already bound to {1}..
        /// </summary>
        internal static string BindMessage6 {
            get {
                return ResourceManager.GetString("BindMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bound to {1}..
        /// </summary>
        internal static string BindMessage7 {
            get {
                return ResourceManager.GetString("BindMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This block cannot be bound.
        /// </summary>
        internal static string BindMessage8 {
            get {
                return ResourceManager.GetString("BindMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t bound..
        /// </summary>
        internal static string BindMessage9 {
            get {
                return ResourceManager.GetString("BindMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BindName {
            get {
                return ResourceManager.GetString("BindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string BindParameter {
            get {
                return ResourceManager.GetString("BindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blockset [block] [rank] - Changes [block] rank to [rank].
        /// </summary>
        internal static string BlockSetHelp {
            get {
                return ResourceManager.GetString("BlockSetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only blocks you can use can be modified.
        /// </summary>
        internal static string BlockSetHelp1 {
            get {
                return ResourceManager.GetString("BlockSetHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available ranks: {0}.
        /// </summary>
        internal static string BlockSetHelp2 {
            get {
                return ResourceManager.GetString("BlockSetHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find block entered.
        /// </summary>
        internal static string BlockSetMessage {
            get {
                return ResourceManager.GetString("BlockSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find rank specified.
        /// </summary>
        internal static string BlockSetMessage1 {
            get {
                return ResourceManager.GetString("BlockSetMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set to a rank higher than yourself..
        /// </summary>
        internal static string BlockSetMessage2 {
            get {
                return ResourceManager.GetString("BlockSetMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify a block set for a higher rank.
        /// </summary>
        internal static string BlockSetMessage3 {
            get {
                return ResourceManager.GetString("BlockSetMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;d{0}&apos;s permission was changed to {1}.
        /// </summary>
        internal static string BlockSetMessage4 {
            get {
                return ResourceManager.GetString("BlockSetMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlockSetName {
            get {
                return ResourceManager.GetString("BlockSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks - Lists all basic blocks.
        /// </summary>
        internal static string BlocksHelp {
            get {
                return ResourceManager.GetString("BlocksHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks all - Lists all complex blocks.
        /// </summary>
        internal static string BlocksHelp1 {
            get {
                return ResourceManager.GetString("BlocksHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks [basic block] - Lists all blocks which look the same.
        /// </summary>
        internal static string BlocksHelp2 {
            get {
                return ResourceManager.GetString("BlocksHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks [complex block] - Lists specific information on block.
        /// </summary>
        internal static string BlocksHelp3 {
            get {
                return ResourceManager.GetString("BlocksHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks &lt;rank&gt; - Lists all blocks &lt;rank&gt; can use.
        /// </summary>
        internal static string BlocksHelp4 {
            get {
                return ResourceManager.GetString("BlocksHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blocks count &lt;block&gt; - Finds total count for &lt;block&gt; in map.
        /// </summary>
        internal static string BlocksHelp5 {
            get {
                return ResourceManager.GetString("BlocksHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic blocks: .
        /// </summary>
        internal static string BlocksMessage {
            get {
                return ResourceManager.GetString("BlocksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;d/blocks all &lt;0/1/2/3/4&gt; {0}will show the rest..
        /// </summary>
        internal static string BlocksMessage1 {
            get {
                return ResourceManager.GetString("BlocksMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;cBlock will appear as a \&quot;{0}\&quot; block.
        /// </summary>
        internal static string BlocksMessage10 {
            get {
                return ResourceManager.GetString("BlocksMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block will allow light through.
        /// </summary>
        internal static string BlocksMessage11 {
            get {
                return ResourceManager.GetString("BlocksMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block effects physics in some way.
        /// </summary>
        internal static string BlocksMessage12 {
            get {
                return ResourceManager.GetString("BlocksMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block will not effect physics in any way.
        /// </summary>
        internal static string BlocksMessage13 {
            get {
                return ResourceManager.GetString("BlocksMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block&apos;s physics will auto-start.
        /// </summary>
        internal static string BlocksMessage14 {
            get {
                return ResourceManager.GetString("BlocksMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is unaffected by explosions.
        /// </summary>
        internal static string BlocksMessage15 {
            get {
                return ResourceManager.GetString("BlocksMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anybody can activate the block.
        /// </summary>
        internal static string BlocksMessage16 {
            get {
                return ResourceManager.GetString("BlocksMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block can be walked through.
        /// </summary>
        internal static string BlocksMessage17 {
            get {
                return ResourceManager.GetString("BlocksMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking through block will kill you.
        /// </summary>
        internal static string BlocksMessage18 {
            get {
                return ResourceManager.GetString("BlocksMessage18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is an ordinary door.
        /// </summary>
        internal static string BlocksMessage19 {
            get {
                return ResourceManager.GetString("BlocksMessage19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex blocks: .
        /// </summary>
        internal static string BlocksMessage2 {
            get {
                return ResourceManager.GetString("BlocksMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is a tdoor, which allows other blocks through when open.
        /// </summary>
        internal static string BlocksMessage20 {
            get {
                return ResourceManager.GetString("BlocksMessage20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is an odoor, which toggles (GLITCHY).
        /// </summary>
        internal static string BlocksMessage21 {
            get {
                return ResourceManager.GetString("BlocksMessage21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block can be activated by walking through it.
        /// </summary>
        internal static string BlocksMessage22 {
            get {
                return ResourceManager.GetString("BlocksMessage22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks which {0} can place: .
        /// </summary>
        internal static string BlocksMessage23 {
            get {
                return ResourceManager.GetString("BlocksMessage23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blocks are specific to this rank.
        /// </summary>
        internal static string BlocksMessage24 {
            get {
                return ResourceManager.GetString("BlocksMessage24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks in this map: {0}.
        /// </summary>
        internal static string BlocksMessage25 {
            get {
                return ResourceManager.GetString("BlocksMessage25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find block specified.
        /// </summary>
        internal static string BlocksMessage26 {
            get {
                return ResourceManager.GetString("BlocksMessage26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blocks were of type \&quot;{0}\.
        /// </summary>
        internal static string BlocksMessage27 {
            get {
                return ResourceManager.GetString("BlocksMessage27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 block was of type \&quot;{0}\.
        /// </summary>
        internal static string BlocksMessage28 {
            get {
                return ResourceManager.GetString("BlocksMessage28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blocks were of type \&quot;{1}\.
        /// </summary>
        internal static string BlocksMessage29 {
            get {
                return ResourceManager.GetString("BlocksMessage29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &amp;d/blocks all &lt;0/1/2/3/4&gt; {0}for a readable list..
        /// </summary>
        internal static string BlocksMessage3 {
            get {
                return ResourceManager.GetString("BlocksMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find block or rank.
        /// </summary>
        internal static string BlocksMessage30 {
            get {
                return ResourceManager.GetString("BlocksMessage30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect syntax.
        /// </summary>
        internal static string BlocksMessage4 {
            get {
                return ResourceManager.GetString("BlocksMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be between 0 and 4.
        /// </summary>
        internal static string BlocksMessage5 {
            get {
                return ResourceManager.GetString("BlocksMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks between {0} and {1}.
        /// </summary>
        internal static string BlocksMessage6 {
            get {
                return ResourceManager.GetString("BlocksMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks which look like \&quot;{0}\&quot;:.
        /// </summary>
        internal static string BlocksMessage7 {
            get {
                return ResourceManager.GetString("BlocksMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Complex Blocks look like \&quot;{0}\.
        /// </summary>
        internal static string BlocksMessage8 {
            get {
                return ResourceManager.GetString("BlocksMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bComplex information for \&quot;{0}\&quot;:.
        /// </summary>
        internal static string BlocksMessage9 {
            get {
                return ResourceManager.GetString("BlocksMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlocksName {
            get {
                return ResourceManager.GetString("BlocksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string BlocksParameter {
            get {
                return ResourceManager.GetString("BlocksParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string BlocksParameter1 {
            get {
                return ResourceManager.GetString("BlocksParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /botadd &lt;name&gt; - Add a  new bot at your position..
        /// </summary>
        internal static string BotAddHelp {
            get {
                return ResourceManager.GetString("BotAddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot name {0} not valid!.
        /// </summary>
        internal static string BotAddMessage {
            get {
                return ResourceManager.GetString("BotAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotAddName {
            get {
                return ResourceManager.GetString("BotAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /botai &lt;add/del&gt; [AI name] &lt;extra&gt; - Adds or deletes [AI name].
        /// </summary>
        internal static string BotAIHelp {
            get {
                return ResourceManager.GetString("BotAIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras: walk, teleport, wait, nod, speed, spin, reset, remove, reverse, linkscript, jump.
        /// </summary>
        internal static string BotAIHelp1 {
            get {
                return ResourceManager.GetString("BotAIHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait, nod and spin can have an extra &apos;0.1 seconds&apos; parameter.
        /// </summary>
        internal static string BotAIHelp2 {
            get {
                return ResourceManager.GetString("BotAIHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nod and spin can also take a &apos;third&apos; speed parameter.
        /// </summary>
        internal static string BotAIHelp3 {
            get {
                return ResourceManager.GetString("BotAIHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed sets a percentage of normal speed.
        /// </summary>
        internal static string BotAIHelp4 {
            get {
                return ResourceManager.GetString("BotAIHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkscript takes a script name as parameter.
        /// </summary>
        internal static string BotAIHelp5 {
            get {
                return ResourceManager.GetString("BotAIHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AI name!.
        /// </summary>
        internal static string BotAIMessage {
            get {
                return ResourceManager.GetString("BotAIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for special AI..
        /// </summary>
        internal static string BotAIMessage1 {
            get {
                return ResourceManager.GetString("BotAIMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find \&quot;{0}\.
        /// </summary>
        internal static string BotAIMessage10 {
            get {
                return ResourceManager.GetString("BotAIMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        internal static string BotAIMessage11 {
            get {
                return ResourceManager.GetString("BotAIMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted the last waypoint from {0}.
        /// </summary>
        internal static string BotAIMessage2 {
            get {
                return ResourceManager.GetString("BotAIMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted &amp;b{0}.
        /// </summary>
        internal static string BotAIMessage3 {
            get {
                return ResourceManager.GetString("BotAIMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified AI..
        /// </summary>
        internal static string BotAIMessage4 {
            get {
                return ResourceManager.GetString("BotAIMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new bot AI: &amp;b{0}.
        /// </summary>
        internal static string BotAIMessage5 {
            get {
                return ResourceManager.GetString("BotAIMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File found is out-of-date. Overwriting.
        /// </summary>
        internal static string BotAIMessage6 {
            get {
                return ResourceManager.GetString("BotAIMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appended to bot AI: &amp;b{0}.
        /// </summary>
        internal static string BotAIMessage7 {
            get {
                return ResourceManager.GetString("BotAIMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when accessing the files. You may need to delete it..
        /// </summary>
        internal static string BotAIMessage8 {
            get {
                return ResourceManager.GetString("BotAIMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkscript requires a script as a parameter.
        /// </summary>
        internal static string BotAIMessage9 {
            get {
                return ResourceManager.GetString("BotAIMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotAIName {
            get {
                return ResourceManager.GetString("BotAIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hunt.
        /// </summary>
        internal static string BotAIParameter {
            get {
                return ResourceManager.GetString("BotAIParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.Command.BotAIParameter.
        /// </summary>
        internal static string BotAIParameter1 {
            get {
                return ResourceManager.GetString("BotAIParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string BotAIParameter2 {
            get {
                return ResourceManager.GetString("BotAIParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to del.
        /// </summary>
        internal static string BotAIParameter3 {
            get {
                return ResourceManager.GetString("BotAIParameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /botremove &lt;name&gt; - Remove a bot on the same level as you.
        /// </summary>
        internal static string BotRemoveHelp {
            get {
                return ResourceManager.GetString("BotRemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no bot {0}!.
        /// </summary>
        internal static string BotRemoveMessage {
            get {
                return ResourceManager.GetString("BotRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is in a different level..
        /// </summary>
        internal static string BotRemoveMessage1 {
            get {
                return ResourceManager.GetString("BotRemoveMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed bot..
        /// </summary>
        internal static string BotRemoveMessage2 {
            get {
                return ResourceManager.GetString("BotRemoveMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotRemoveName {
            get {
                return ResourceManager.GetString("BotRemoveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string BotRemoveParameter {
            get {
                return ResourceManager.GetString("BotRemoveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /botset &lt;bot&gt; &lt;AI script&gt; - Makes &lt;bot&gt; do &lt;AI script&gt;.
        /// </summary>
        internal static string BotSetHelp {
            get {
                return ResourceManager.GetString("BotSetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special AI scripts: Kill and Hunt.
        /// </summary>
        internal static string BotSetHelp1 {
            get {
                return ResourceManager.GetString("BotSetHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s AI was turned off..
        /// </summary>
        internal static string BotSetMessage {
            get {
                return ResourceManager.GetString("BotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified Bot.
        /// </summary>
        internal static string BotSetMessage1 {
            get {
                return ResourceManager.GetString("BotSetMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s hunt instinct: {1}.
        /// </summary>
        internal static string BotSetMessage2 {
            get {
                return ResourceManager.GetString("BotSetMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an OP may toggle killer instinct..
        /// </summary>
        internal static string BotSetMessage3 {
            get {
                return ResourceManager.GetString("BotSetMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s kill instinct: {1}.
        /// </summary>
        internal static string BotSetMessage4 {
            get {
                return ResourceManager.GetString("BotSetMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified AI..
        /// </summary>
        internal static string BotSetMessage5 {
            get {
                return ResourceManager.GetString("BotSetMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file version. Remake.
        /// </summary>
        internal static string BotSetMessage6 {
            get {
                return ResourceManager.GetString("BotSetMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI file corrupt..
        /// </summary>
        internal static string BotSetMessage7 {
            get {
                return ResourceManager.GetString("BotSetMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s AI is now set to {1}.
        /// </summary>
        internal static string BotSetMessage8 {
            get {
                return ResourceManager.GetString("BotSetMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string BotSetMessage9 {
            get {
                return ResourceManager.GetString("BotSetMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotSetName {
            get {
                return ResourceManager.GetString("BotSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hunt.
        /// </summary>
        internal static string BotSetParameter {
            get {
                return ResourceManager.GetString("BotSetParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kill.
        /// </summary>
        internal static string BotSetParameter1 {
            get {
                return ResourceManager.GetString("BotSetParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jump.
        /// </summary>
        internal static string BotSetParameter10 {
            get {
                return ResourceManager.GetString("BotSetParameter10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string BotSetParameter11 {
            get {
                return ResourceManager.GetString("BotSetParameter11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walk.
        /// </summary>
        internal static string BotSetParameter2 {
            get {
                return ResourceManager.GetString("BotSetParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teleport.
        /// </summary>
        internal static string BotSetParameter3 {
            get {
                return ResourceManager.GetString("BotSetParameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait.
        /// </summary>
        internal static string BotSetParameter4 {
            get {
                return ResourceManager.GetString("BotSetParameter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        internal static string BotSetParameter5 {
            get {
                return ResourceManager.GetString("BotSetParameter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nod.
        /// </summary>
        internal static string BotSetParameter6 {
            get {
                return ResourceManager.GetString("BotSetParameter6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spin.
        /// </summary>
        internal static string BotSetParameter7 {
            get {
                return ResourceManager.GetString("BotSetParameter7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkscript.
        /// </summary>
        internal static string BotSetParameter8 {
            get {
                return ResourceManager.GetString("BotSetParameter8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        internal static string BotSetParameter9 {
            get {
                return ResourceManager.GetString("BotSetParameter9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /bots - Shows a list of bots, their AIs and levels.
        /// </summary>
        internal static string BotsHelp {
            get {
                return ResourceManager.GetString("BotsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;1Bots: .
        /// </summary>
        internal static string BotsMessage {
            get {
                return ResourceManager.GetString("BotsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bots are alive..
        /// </summary>
        internal static string BotsMessage1 {
            get {
                return ResourceManager.GetString("BotsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotsName {
            get {
                return ResourceManager.GetString("BotsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /botsummon &lt;name&gt; - Summons a bot to your position..
        /// </summary>
        internal static string BotSummonHelp {
            get {
                return ResourceManager.GetString("BotSummonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no bot {0}!.
        /// </summary>
        internal static string BotSummonMessage {
            get {
                return ResourceManager.GetString("BotSummonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is in a different level..
        /// </summary>
        internal static string BotSummonMessage1 {
            get {
                return ResourceManager.GetString("BotSummonMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BotSummonName {
            get {
                return ResourceManager.GetString("BotSummonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /buy - lets you buy stuff, e.g. /buy life, /buy water.
        /// </summary>
        internal static string BuyHelp {
            get {
                return ResourceManager.GetString("BuyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BuyName {
            get {
                return ResourceManager.GetString("BuyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string BuyParameter {
            get {
                return ResourceManager.GetString("BuyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cpe - Admin super secret command..
        /// </summary>
        internal static string ChangePlayerExpHelp {
            get {
                return ResourceManager.GetString("ChangePlayerExpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has to be 2 arguments!.
        /// </summary>
        internal static string ChangePlayerExpMessage {
            get {
                return ResourceManager.GetString("ChangePlayerExpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number.
        /// </summary>
        internal static string ChangePlayerExpMessage1 {
            get {
                return ResourceManager.GetString("ChangePlayerExpMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the player..
        /// </summary>
        internal static string ChangePlayerExpMessage2 {
            get {
                return ResourceManager.GetString("ChangePlayerExpMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player experience has been changed by {0} exp points.
        /// </summary>
        internal static string ChangePlayerExpMessage3 {
            get {
                return ResourceManager.GetString("ChangePlayerExpMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePlayerExpName {
            get {
                return ResourceManager.GetString("ChangePlayerExpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /abort - Cancels an action..
        /// </summary>
        internal static string CmdAbortHelp {
            get {
                return ResourceManager.GetString("CmdAbortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every toggle or action was aborted..
        /// </summary>
        internal static string CmdAbortMessage {
            get {
                return ResourceManager.GetString("CmdAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CmdAbortName {
            get {
                return ResourceManager.GetString("CmdAbortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block ({0},{1},{2}): .
        /// </summary>
        internal static string CmdAboutBlock {
            get {
                return ResourceManager.GetString("CmdAboutBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break/build a block to display information..
        /// </summary>
        internal static string CmdAboutBreakForInfo {
            get {
                return ResourceManager.GetString("CmdAboutBreakForInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;3Created by {0}, using%3 {1}.
        /// </summary>
        internal static string CmdAboutCreatedBy {
            get {
                return ResourceManager.GetString("CmdAboutCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;4Destroyed by {0}, using%3 {1}.
        /// </summary>
        internal static string CmdAboutDestroyedBy {
            get {
                return ResourceManager.GetString("CmdAboutDestroyedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /about - Displays information about a block..
        /// </summary>
        internal static string CmdAboutHelp {
            get {
                return ResourceManager.GetString("CmdAboutHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Block({0},{1},{2})!.
        /// </summary>
        internal static string CmdAboutInvalidBlock {
            get {
                return ResourceManager.GetString("CmdAboutInvalidBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics information:&amp;a {0}.
        /// </summary>
        internal static string CmdAboutPhysics {
            get {
                return ResourceManager.GetString("CmdAboutPhysics", resourceCulture);
            }
        }
    }
}
