//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDzienny_.MCDzienny.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LavaSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LavaSystem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDzienny_.MCDzienny.Lang.LavaSystem", typeof(LavaSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %bLava stays %aCALM%b in this round..
        /// </summary>
        public static string LavaStateCalm {
            get {
                return ResourceManager.GetString("LavaStateCalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %bLava is %9DISTURBED%b in this round..
        /// </summary>
        public static string LavaStateDisturbed {
            get {
                return ResourceManager.GetString("LavaStateDisturbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %bLava becomes %cFURIOUS%b in this round..
        /// </summary>
        public static string LavaStateFurious {
            get {
                return ResourceManager.GetString("LavaStateFurious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %bLava gets %cWILD%b in this round!!!.
        /// </summary>
        public static string LavaStateWild {
            get {
                return ResourceManager.GetString("LavaStateWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d* %fAuthor:%b {0}.
        /// </summary>
        public static string MapAuthor {
            get {
                return ResourceManager.GetString("MapAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d* %fMap name:%b {0}.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next map is: {0}.
        /// </summary>
        public static string MapNext {
            get {
                return ResourceManager.GetString("MapNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %aRating for this map is:%c {0} %alikes,%c {1} %adislikes..
        /// </summary>
        public static string MapRatingResults {
            get {
                return ResourceManager.GetString("MapRatingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %a(You can rate this map by typing /like or /dislike).
        /// </summary>
        public static string MapRatingTip {
            get {
                return ResourceManager.GetString("MapRatingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gained {0} {1}..
        /// </summary>
        public static string RewardMessageAboveSea {
            get {
                return ResourceManager.GetString("RewardMessageAboveSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gained {0} {1}. {2}.
        /// </summary>
        public static string RewardMessageBelowSea {
            get {
                return ResourceManager.GetString("RewardMessageBelowSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were rewarded {0} less than normal because you were below the Sea Level..
        /// </summary>
        public static string RewardMessageBelowSea2 {
            get {
                return ResourceManager.GetString("RewardMessageBelowSea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have voted for 1st map..
        /// </summary>
        public static string Voted1 {
            get {
                return ResourceManager.GetString("Voted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have voted for 2nd map..
        /// </summary>
        public static string Voted2 {
            get {
                return ResourceManager.GetString("Voted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have voted for 3rd map..
        /// </summary>
        public static string Voted3 {
            get {
                return ResourceManager.GetString("Voted3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for the next map.
        /// </summary>
        public static string VoteForNextMap {
            get {
                return ResourceManager.GetString("VoteForNextMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write %c1{0} for {1}, %c2{0} for {2}, %c3{0} for {3}.
        /// </summary>
        public static string VoteOptions {
            get {
                return ResourceManager.GetString("VoteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of voting:.
        /// </summary>
        public static string VoteResults {
            get {
                return ResourceManager.GetString("VoteResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map: {0} - {1}, {2} - {3}, {4} - {5} votes..
        /// </summary>
        public static string VoteResults2 {
            get {
                return ResourceManager.GetString("VoteResults2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to vote write 1 or 2 or 3..
        /// </summary>
        public static string VoteTip {
            get {
                return ResourceManager.GetString("VoteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already voted. Wait a moment till the end of voting..
        /// </summary>
        public static string WarningAlreadyVoted {
            get {
                return ResourceManager.GetString("WarningAlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were too close to the map spawn!! You have to be at least {0} blocks away from spawn point to be the winner..
        /// </summary>
        public static string WarningTooCloseToSpawn {
            get {
                return ResourceManager.GetString("WarningTooCloseToSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the highest rank possible..
        /// </summary>
        public static string YouHaveTheHighestRank {
            get {
                return ResourceManager.GetString("YouHaveTheHighestRank", resourceCulture);
            }
        }
    }
}
