//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDzienny_.MCDzienny.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Level {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Level() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDzienny_.MCDzienny.Lang.Level", typeof(Level).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED TO SAVE : {0}.
        /// </summary>
        public static string ErrorMapSaveGlobalMessage {
            get {
                return ResourceManager.GetString("ErrorMapSaveGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;3{0} was unloaded..
        /// </summary>
        public static string MapUnloadedGlobalMessage {
            get {
                return ResourceManager.GetString("MapUnloadedGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to place gold rock on this map..
        /// </summary>
        public static string NotAllowedToPlaceGoldRock {
            get {
                return ResourceManager.GetString("NotAllowedToPlaceGoldRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run out of doors. Check the /store..
        /// </summary>
        public static string OutOfDoors {
            get {
                return ResourceManager.GetString("OutOfDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run out of sponges. Check the /store..
        /// </summary>
        public static string OutOfSponges {
            get {
                return ResourceManager.GetString("OutOfSponges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run out of water. Check the /store..
        /// </summary>
        public static string OutOfWater {
            get {
                return ResourceManager.GetString("OutOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics shutdown on&amp;b {0}.
        /// </summary>
        public static string PhysicsShutdownGlobalMessage {
            get {
                return ResourceManager.GetString("PhysicsShutdownGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics warning!.
        /// </summary>
        public static string PhysicsWarning {
            get {
                return ResourceManager.GetString("PhysicsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This block is owned by {0}..
        /// </summary>
        public static string WarningBlockOwned {
            get {
                return ResourceManager.GetString("WarningBlockOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify block placed by someone with higher level than yours..
        /// </summary>
        public static string WarningBlockProtectedByLevel {
            get {
                return ResourceManager.GetString("WarningBlockProtectedByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} to build here.
        /// </summary>
        public static string WarningBuildPermission {
            get {
                return ResourceManager.GetString("WarningBuildPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This zone belongs to&amp;b {0}..
        /// </summary>
        public static string ZoneBelongsTo {
            get {
                return ResourceManager.GetString("ZoneBelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This zone belongs to no one..
        /// </summary>
        public static string ZoneBelongsToNoOne {
            get {
                return ResourceManager.GetString("ZoneBelongsToNoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone deleted for&amp;b {0}.
        /// </summary>
        public static string ZoneDeleted {
            get {
                return ResourceManager.GetString("ZoneDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zones found to delete..
        /// </summary>
        public static string ZoneNotFoundNotDeleted {
            get {
                return ResourceManager.GetString("ZoneNotFoundNotDeleted", resourceCulture);
            }
        }
    }
}
