//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDzienny_.MCDzienny.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Player {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Player() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDzienny_.MCDzienny.Lang.Player", typeof(Player).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto: Not moved for {0} minutes.
        /// </summary>
        public static string AfkMessage {
            get {
                return ResourceManager.GetString("AfkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0}- is no longer AFK.
        /// </summary>
        public static string AfkNoLonger {
            get {
                return ResourceManager.GetString("AfkNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message appended!.
        /// </summary>
        public static string ChatAppended {
            get {
                return ResourceManager.GetString("ChatAppended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal character in chat message!.
        /// </summary>
        public static string ChatIllegalCharacter {
            get {
                return ResourceManager.GetString("ChatIllegalCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat moderation is on, you cannot speak..
        /// </summary>
        public static string ChatModeration {
            get {
                return ResourceManager.GetString("ChatModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are muted..
        /// </summary>
        public static string ChatMuted {
            get {
                return ResourceManager.GetString("ChatMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message entered.
        /// </summary>
        public static string ChatNoMessageEntered {
            get {
                return ResourceManager.GetString("ChatNoMessageEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are muted for {0} seconds..
        /// </summary>
        public static string ChatTempMutedTime {
            get {
                return ResourceManager.GetString("ChatTempMutedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Ops &amp;f-{0}&amp;f- {1}.
        /// </summary>
        public static string ChatToOps {
            get {
                return ResourceManager.GetString("ChatToOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed..
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use any commands while jailed..
        /// </summary>
        public static string CommandJailWarning {
            get {
                return ResourceManager.GetString("CommandJailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CMD is stored on /{0}.
        /// </summary>
        public static string CommandNoBind {
            get {
                return ResourceManager.GetString("CommandNoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command entered..
        /// </summary>
        public static string CommandNoEntered {
            get {
                return ResourceManager.GetString("CommandNoEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to use &quot;{0}&quot;!.
        /// </summary>
        public static string CommandNotAllowedToUse {
            get {
                return ResourceManager.GetString("CommandNotAllowedToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use /{0} while muted or jokered..
        /// </summary>
        public static string CommandNoUseWhenMuted {
            get {
                return ResourceManager.GetString("CommandNoUseWhenMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player &quot;{0}&quot; doesn&apos;t exist!.
        /// </summary>
        public static string CommandPlayerNonexistent {
            get {
                return ResourceManager.GetString("CommandPlayerNonexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command &quot;{0}&quot;!.
        /// </summary>
        public static string CommandUnknown {
            get {
                return ResourceManager.GetString("CommandUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to talk to yourself, huh?.
        /// </summary>
        public static string CommandUsedOneself {
            get {
                return ResourceManager.GetString("CommandUsedOneself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has died&amp;3 {1} times.
        /// </summary>
        public static string DiedTimesGlobalMessage {
            get {
                return ResourceManager.GetString("DiedTimesGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when using the command!.
        /// </summary>
        public static string ErrorCommand {
            get {
                return ResourceManager.GetString("ErrorCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;World&gt;.
        /// </summary>
        public static string GlobalChatWorldTag {
            get {
                return ResourceManager.GetString("GlobalChatWorldTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;c- {0} kicked ({1})..
        /// </summary>
        public static string GlobalMessageKicked {
            get {
                return ResourceManager.GetString("GlobalMessageKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left the game..
        /// </summary>
        public static string GlobalMessageLeftGame {
            get {
                return ResourceManager.GetString("GlobalMessageLeftGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kicked ({1})..
        /// </summary>
        public static string IrcMessageKicked {
            get {
                return ResourceManager.GetString("IrcMessageKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined the game..
        /// </summary>
        public static string JoinGlobalMessage {
            get {
                return ResourceManager.GetString("JoinGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were kicked for being afk for over {0} min..
        /// </summary>
        public static string KickAfk {
            get {
                return ResourceManager.GetString("KickAfk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged in!.
        /// </summary>
        public static string KickAlreadyLogged {
            get {
                return ResourceManager.GetString("KickAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected..
        /// </summary>
        public static string KickDisconnected {
            get {
                return ResourceManager.GetString("KickDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn hacks off!.
        /// </summary>
        public static string KickHacks {
            get {
                return ResourceManager.GetString("KickHacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal name!.
        /// </summary>
        public static string KickIllegalName {
            get {
                return ResourceManager.GetString("KickIllegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone logged in as you!.
        /// </summary>
        public static string KickLoggedAsYou {
            get {
                return ResourceManager.GetString("KickLoggedAsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed! Try again..
        /// </summary>
        public static string KickLoginFailed {
            get {
                return ResourceManager.GetString("KickLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server full!.
        /// </summary>
        public static string KickServerFull {
            get {
                return ResourceManager.GetString("KickServerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re still banned (temporary ban)!.
        /// </summary>
        public static string KickTempBan {
            get {
                return ResourceManager.GetString("KickTempBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown block action!.
        /// </summary>
        public static string KickUnknownAction {
            get {
                return ResourceManager.GetString("KickUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong version!.
        /// </summary>
        public static string KickWrongVersion {
            get {
                return ResourceManager.GetString("KickWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lately known as:.
        /// </summary>
        public static string LatelyKnownAs {
            get {
                return ResourceManager.GetString("LatelyKnownAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string VoteDecisionNo {
            get {
                return ResourceManager.GetString("VoteDecisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string VoteDecisionNoShortcut {
            get {
                return ResourceManager.GetString("VoteDecisionNoShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string VoteDecisionYes {
            get {
                return ResourceManager.GetString("VoteDecisionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string VoteDecisionYesShortcut {
            get {
                return ResourceManager.GetString("VoteDecisionYesShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for the vote!.
        /// </summary>
        public static string VoteThanks {
            get {
                return ResourceManager.GetString("VoteThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is breaking something.
        /// </summary>
        public static string WarningBreakingBlocks {
            get {
                return ResourceManager.GetString("WarningBreakingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t build that far away..
        /// </summary>
        public static string WarningBuiltTooFar {
            get {
                return ResourceManager.GetString("WarningBuiltTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not allowed to build this far down!.
        /// </summary>
        public static string WarningBuiltTooLow {
            get {
                return ResourceManager.GetString("WarningBuiltTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build here!.
        /// </summary>
        public static string WarningCantBuildHere {
            get {
                return ResourceManager.GetString("WarningCantBuildHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is active, you cant disturb it!.
        /// </summary>
        public static string WarningCantDisturbBlock {
            get {
                return ResourceManager.GetString("WarningCantDisturbBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t place this block type!.
        /// </summary>
        public static string WarningDisallowedBlockType {
            get {
                return ResourceManager.GetString("WarningDisallowedBlockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message was stored..
        /// </summary>
        public static string WarningNoMessageStored {
            get {
                return ResourceManager.GetString("WarningNoMessageStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map the portal goes to isn&apos;t loaded..
        /// </summary>
        public static string WarningPortalDestinationUnloaded {
            get {
                return ResourceManager.GetString("WarningPortalDestinationUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal has no exit..
        /// </summary>
        public static string WarningPortalHasNoExit {
            get {
                return ResourceManager.GetString("WarningPortalHasNoExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to build pillars that are so high..
        /// </summary>
        public static string WarningTooHighPillar {
            get {
                return ResourceManager.GetString("WarningTooHighPillar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! {0}! You&apos;ve been here {1} times!.
        /// </summary>
        public static string WelcomeAnotherVisit {
            get {
                return ResourceManager.GetString("WelcomeAnotherVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} awards..
        /// </summary>
        public static string WelcomeAwards {
            get {
                return ResourceManager.GetString("WelcomeAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}! This is your first visit..
        /// </summary>
        public static string WelcomeFirstVisit {
            get {
                return ResourceManager.GetString("WelcomeFirstVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;cYou have&amp;f {0} &amp;cmessages in /inbox.
        /// </summary>
        public static string WelcomeInbox {
            get {
                return ResourceManager.GetString("WelcomeInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowlag mode is currently &amp;aON..
        /// </summary>
        public static string WelcomeLowLag {
            get {
                return ResourceManager.GetString("WelcomeLowLag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have modified&amp;a {0} blocks!.
        /// </summary>
        public static string WelcomeModified {
            get {
                return ResourceManager.GetString("WelcomeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have&amp;a {0}.
        /// </summary>
        public static string WelcomeMoney {
            get {
                return ResourceManager.GetString("WelcomeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently&amp;a {0} player online..
        /// </summary>
        public static string WelcomePlayerCount {
            get {
                return ResourceManager.GetString("WelcomePlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently&amp;a {0} players online..
        /// </summary>
        public static string WelcomePlayersCount {
            get {
                return ResourceManager.GetString("WelcomePlayersCount", resourceCulture);
            }
        }
    }
}
