//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDzienny_.MCDzienny.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDzienny_.MCDzienny.Lang.Store", typeof(Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought armor. Now you are fully protected from lava for the next 45 seconds!.
        /// </summary>
        public static string BoughtArmor {
            get {
                return ResourceManager.GetString("BoughtArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought color. In order to use it write /color [color]..
        /// </summary>
        public static string BoughtColor {
            get {
                return ResourceManager.GetString("BoughtColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to change color of your nick write /color [color]..
        /// </summary>
        public static string BoughtColorTip {
            get {
                return ResourceManager.GetString("BoughtColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought doors..
        /// </summary>
        public static string BoughtDoors {
            get {
                return ResourceManager.GetString("BoughtDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought a farewell message. In order to use it write /farewell [message]..
        /// </summary>
        public static string BoughtFarewell {
            get {
                return ResourceManager.GetString("BoughtFarewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to set your farewell message use /farewell [message]..
        /// </summary>
        public static string BoughtFarewellTip {
            get {
                return ResourceManager.GetString("BoughtFarewellTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought hammer..
        /// </summary>
        public static string BoughtHammer {
            get {
                return ResourceManager.GetString("BoughtHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought a life..
        /// </summary>
        public static string BoughtLife {
            get {
                return ResourceManager.GetString("BoughtLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot buy higher rank..
        /// </summary>
        public static string BoughtPromotionWarning {
            get {
                return ResourceManager.GetString("BoughtPromotionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought sponges..
        /// </summary>
        public static string BoughtSponges {
            get {
                return ResourceManager.GetString("BoughtSponges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought teleport. In order to use it write /tp [player]..
        /// </summary>
        public static string BoughtTeleport {
            get {
                return ResourceManager.GetString("BoughtTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use teleport write /tp [player]..
        /// </summary>
        public static string BoughtTeleportTip {
            get {
                return ResourceManager.GetString("BoughtTeleportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought title. In order to use it write /title (your title)..
        /// </summary>
        public static string BoughtTitle {
            get {
                return ResourceManager.GetString("BoughtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought color. In order to use it write /titlecolor [color]..
        /// </summary>
        public static string BoughtTitleColor {
            get {
                return ResourceManager.GetString("BoughtTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to change color of your title write /titlecolor [color]..
        /// </summary>
        public static string BoughtTitleColorTip {
            get {
                return ResourceManager.GetString("BoughtTitleColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to change title write /title (your title)..
        /// </summary>
        public static string BoughtTitleTip {
            get {
                return ResourceManager.GetString("BoughtTitleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought water..
        /// </summary>
        public static string BoughtWater {
            get {
                return ResourceManager.GetString("BoughtWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bought a welcome message. In order to use it write /welcome [message]..
        /// </summary>
        public static string BoughtWelcome {
            get {
                return ResourceManager.GetString("BoughtWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to set your welcome message use /welcome [message]..
        /// </summary>
        public static string BoughtWelcomeTip {
            get {
                return ResourceManager.GetString("BoughtWelcomeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d For more items write &apos;/store more&apos; !.
        /// </summary>
        public static string MoreItemsTip {
            get {
                return ResourceManager.GetString("MoreItemsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough {0}..
        /// </summary>
        public static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %c {0}: %dpromotion - {1} {2} - promotes you to {3} rank..
        /// </summary>
        public static string PromotionItem {
            get {
                return ResourceManager.GetString("PromotionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available..
        /// </summary>
        public static string PromotionNotAvailable {
            get {
                return ResourceManager.GetString("PromotionNotAvailable", resourceCulture);
            }
        }
    }
}
